
export const APP_LOADING = 'APP_LOADING' ;
export const SET_NETWORKING = 'SET_NETWORKING';
export const SET_STORAGE_AVAILABLE = 'SET_STORAGE_AVAILABLE';

export const EDIT_DIMENSION_OPTION = "EDIT_DIMENSION_OPTION"

export const ADD_DIMENSION_OPTION = 'ADD_DIMENSION_OPTION';
export const UPDATE_DIMENSION_OPTION = 'UPDATE_DIMENSION_OPTION';
export const REMOVE_DIMENSION_OPTION = 'REMOVE_DIMENSION_OPTION';
export const SORT_DIMENSION_OPTION = 'SORT_DIMENSION_OPTION';

export const SET_DIMENSION_THRESHOLDS = 'SET_DIMENSION_THRESHOLDS';

export const LOAD_DIMENSIONS = 'LOAD_DIMENSIONS';
export const ADD_DIMENSION = 'ADD_DIMENSION';
export const UPDATE_DIMENSION = 'UPDATE_DIMENSION';
export const REMOVE_DIMENSION = 'REMOVE_DIMENSION';
export const SET_VALUE = 'SET_VALUE';
export const LOAD_VALUES = 'LOAD_VALUES';
export const REMOVE_VALUE = 'REMOVE_VALUE';

export const SET_DIMENSION_THRESHOLD = 'SET_DIMENSION_THRESHOLD';
export const SET_DATE = 'SET_DATE';