
export const APP_LOADING = 'APP_LOADING' ;
export const SET_NETWORKING = 'SET_NETWORKING';
export const SET_STORAGE_AVAILABLE = 'SET_STORAGE_AVAILABLE';

export const EDIT_DIMENSION_OPTION = "EDIT_DIMENSION_OPTION"

export const ADD_DIMENSION_OPTION = 'ADD_DIMENSION_OPTION';
export const ADD_DIMENSION_OPTION_FAILED = 'ADD_DIMENSION_OPTION_FAILED';
export const ADD_DIMENSION_OPTION_SUCCESS = 'ADD_DIMENSION_OPTION_SUCCESS';
export const UPDATE_DIMENSION_OPTION = 'UPDATE_DIMENSION_OPTION';
export const UPDATE_DIMENSION_OPTION_SUCCESS = 'UPDATE_DIMENSION_OPTION_SUCCESS';
export const UPDATE_DIMENSION_OPTION_FAILED = 'UPDATE_DIMENSION_OPTION_FAILED';
export const REMOVE_DIMENSION_OPTION = 'REMOVE_DIMENSION_OPTION';
export const REMOVE_DIMENSION_OPTION_SUCCESS = 'REMOVE_DIMENSION_OPTION_SUCCESS';
export const REMOVE_DIMENSION_OPTION_FAILED = 'REMOVE_DIMENSION_OPTION_FAILED';
export const SORT_DIMENSION_OPTION = 'SORT_DIMENSION_OPTION';

export const SET_DIMENSION_THRESHOLDS = 'SET_DIMENSION_THRESHOLDS';

export const LOAD_DIMENSIONS = 'LOAD_DIMENSIONS';
export const LOAD_DIMENSIONS_SUCCESS = 'LOAD_DIMENSIONS_SUCCESS';
export const LOAD_DIMENSIONS_FAILED = 'LOAD_DIMENSIONS_FAILED';
export const ADD_DIMENSION = 'ADD_DIMENSION';
export const ADD_DIMENSION_SUCCESS = 'ADD_DIMENSION_SUCCESS';
export const ADD_DIMENSION_FAILED = 'ADD_DIMENSION_FAILED';
export const UPDATE_DIMENSION = 'UPDATE_DIMENSION';
export const UPDATE_DIMENSION_SUCCESS = 'UPDATE_DIMENSION_SUCCESS';
export const UPDATE_DIMENSION_FAILED = 'UPDATE_DIMENSION_FAILED';
export const REMOVE_DIMENSION = 'REMOVE_DIMENSION';
export const REMOVE_DIMENSION_SUCCESS = 'REMOVE_DIMENSION_SUCCESS';
export const REMOVE_DIMENSION_FAILED = 'REMOVE_DIMENSION_FAILED';
export const SET_VALUE = 'SET_VALUE';
export const SET_VALUE_SUCCESS = 'SET_VALUE_SUCESS';
export const SET_VALUE_FAILED = 'SET_VALUE_FAILED';
export const LOAD_VALUES = 'LOAD_VALUES';
export const LOAD_VALUES_SUCCESS = 'LOAD_VALUES_SUCCESS' ;
export const LOAD_VALUES_FAILED = 'LOAD_VALUES_FAILED' ;
export const REMOVE_VALUE = 'REMOVE_VALUE';
export const REMOVE_VALUE_SUCCESS = 'REMOVE_VALUE_SUCCESS';
export const REMOVE_VALUE_FAILED = 'REMOVE_VALUE_FAILED';

export const SET_DIMENSION_THRESHOLD = 'SET_DIMENSION_THRESHOLD';
export const SET_DIMENSION_THRESHOLD_SUCCESS = 'SET_DIMENSION_THRESHOLD_SUCCESS';
export const SET_DIMENSION_THRESHOLD_FAILED = 'SET_DIMENSION_THRESHOLD_FAILED';

export const SET_DATE = 'SET_DATE';