
export const APP_LOADING = 'APP_LOADING' ;
export const SET_NETWORKING = 'SET_NETWORKING';
export const SET_STORAGE_AVAILABLE = 'SET_STORAGE_AVAILABLE';

export const LOAD_DIMENSIONS = 'LOAD_DIMENSIONS';
export const LOAD_DIMENSIONS_SUCCESS = 'LOAD_DIMENSIONS_SUCCESS';
export const LOAD_DIMENSIONS_FAILED = 'LOAD_DIMENSIONS_FAILED';
export const ADD_DIMENSION = 'ADD_DIMENSION';
export const SET_VALUE = 'SET_VALUE';
export const SET_VALUE_SUCCESS = 'SET_VALUE_SUCESS';
export const SET_VALUE_FAILED = 'SET_VALUE_FAILED';
export const LOAD_VALUES = 'LOAD_VALUES';
export const LOAD_VALUES_SUCCESS = 'LOAD_VALUES_SUCCESS' ;
export const LOAD_VALUES_FAILED = 'LOAD_VALUES_FAILED' ;

export const SET_DATE = 'SET_DATE';