
export const APP_LOADING = 'APP_LOADING' 
export const SET_NETWORKING = 'SET_NETWORKING'
export const SET_STORAGE_AVAILABLE = 'SET_STORAGE_AVAILABLE'

export const SET_OPTION = 'CREATE_OPTION'
// export const UPDATE_OPTION = 'UPDATE_OPTION'
export const DELETE_OPTION = 'DELETE_OPTION'
export const EDIT_OPTION = "EDIT_OPTION"
export const SORT_OPTION = 'SORT_OPTION'

export const SET_DIMENSION_THRESHOLDS = 'SET_DIMENSION_THRESHOLDS'

// export const LOAD_DIMENSIONS = 'LOAD_DIMENSIONS'
export const CREATE_DIMENSION = 'CREATE_DIMENSION'
export const UPDATE_DIMENSION = 'UPDATE_DIMENSION'
export const DELETE_DIMENSION = 'DELETE_DIMENSION'
export const SORT_DIMENSIONS = 'SORT_DIMENSIONS'

export const SET_VALUE = 'SET_VALUE'
// export const LOAD_VALUES = 'LOAD_VALUES'
export const DELETE_VALUE = 'DELETE_VALUE'

export const SET_DIMENSION_THRESHOLD = 'SET_DIMENSION_THRESHOLD'
export const SET_DATE = 'SET_DATE'

export const ORDINAL = 1
export const NUMERICAL = 2